
###Creating url shorter(post request)
POST http://localhost:4000/shorturls
Content-Type: application/json

{
  "url": "https://example.com", 
  "validity": 30,
  "shortcode": "sneha123"
}

### gettting the url stats (get request)
GET http://localhost:4000/shorturls/sneha123

